apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeplug
  name: kubeplug-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: kubeplug
