# permissions for end users to view rabbitmqs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmq-viewer-role
rules:
- apiGroups:
  - kubeplug.com
  resources:
  - rabbitmqs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeplug.com
  resources:
  - rabbitmqs/status
  verbs:
  - get
