apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: kubeplug
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeplug
  namespace: system
  labels:
    app: kubeplug
spec:
  selector:
    matchLabels:
      app: kubeplug
  replicas: 1
  template:
    metadata:
      labels:
        app: kubeplug
    spec:
      containers:
      - command:
        - /kubeplug
        args:
        - --enable-leader-election
        image: kubeplug:latest
        name: kubeplug
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
